spring:
  application:
    name: API-GATEWAY

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    account-service:
       path: /account/**
       serviceId: ACCOUNT-SERVICE
    book-service:
       path: /book/**
       serviceId: BOOK-SERVICE
    order-service:
       path: /order/**
       serviceId: ORDER-SERVICE
    shipping-service:
       path: /shipping/**
       serviceId: SHIPPING-SERVICE      
  host:
    socket-timeout-millis: 30000       