spring:
  application:
    name: shipping-service
  
server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
